USE the_burgeoning_blog;
SET QUOTED_IDENTIFIER ON;
CREATE TABLE [dbo].[Blogs](
    [Id] INT PRIMARY KEY IDENTITY(1,1),
	[Title] NVARCHAR(100) NOT NULL,
	[Body] NVARCHAR(MAX) NOT NULL,
	[Tags] NVARCHAR(MAX) NOT NULL,
	[Likes] INT NOT NULL,
	[WriterId] INT CONSTRAINT fk_writer_blog  REFERENCES [dbo].[Writers]([id]) 
	    ON UPDATE CASCADE
		ON DELETE NO ACTION,
	[DateOfPublishing] DATETIME2 DEFAULT(SYSDATETIME())  
);

ALTER TABLE [dbo].[Blogs] ADD [IsDeleted] INT NOT NULL DEFAULT(0);
ALTER TABLE [dbo].[Blogs] ADD CONSTRAINT df_likes DEFAULT(0) for [Likes];

BEGIN TRANSACTION;
ALTER TABLE [dbo].[Blogs]
    ADD [StartTime] DATETIME2(3)  GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT(SYSDATETIME()),
	[EndTime] DATETIME2(3)  GENERATED ALWAYS AS ROW END DEFAULT('99991231 23:59:59.999'),
	PERIOD FOR SYSTEM_TIME ([StartTime],[EndTime]);

ALTER TABLE [dbo].[Blogs]
    SET ( SYSTEM_VERSIONING = ON ( HISTORY_TABLE = dbo.BlogsHistory ) );
COMMIT TRANSACTION;



