USE the_burgeoning_blog;
SET QUOTED_IDENTIFIER ON;
CREATE TABLE [dbo].[Writers](
    [Id] INT CONSTRAINT writer_id_primary_key PRIMARY KEY IDENTITY(1,1),
    [FirstName] NVARCHAR(50) NOT NULL,
    [LastName] NVARCHAR(50) NOT NULL,
    [Email] NVARCHAR(200) NOT NULL, 
    [PhoneNUmber] INT NOT NULL, 
    [DateOfBirth] DATETIME2 DEFAULT(SYSDATETIME()),
    [Active] BIT DEFAULT(1)
);

ALTER TABLE [dbo].[writers] ADD [Password] VARCHAR(200) NOT NULL;

BEGIN TRANSACTION;
ALTER TABLE [dbo].[Writers]
    ADD [StartTime] DATETIME2(3)  GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT(SYSDATETIME()),
	[EndTime] DATETIME2(3)  GENERATED ALWAYS AS ROW END DEFAULT('99991231 23:59:59.999'),
	PERIOD FOR SYSTEM_TIME ([StartTime],[EndTime]);

ALTER TABLE [dbo].[Writers]
    SET ( SYSTEM_VERSIONING = ON ( HISTORY_TABLE = dbo.WritersHistory));
COMMIT TRANSACTION;

ALTER TABLE [dbo].[Writers] ALTER COLUMN [PhoneNUmber] VARCHAR(13) NOT NULL;

ALTER TABLE [dbo].[Writers]  ADD CONSTRAINT uq_writer_email UNIQUE(Email);
